# Welcome to PyRun!

# Need to install more packages? Just edit this file.

# Add packages from conda-forge under "dependencies:"
# Packages from PyPI should be added under "pip:"

name: base
channels:
  - conda-forge
dependencies:
  - python==3.8
  - git
  - ipykernel
  - ipywidgets
  - fsspec
  - matplotlib
  - numpy
  - tqdm
  - xarray
  - h5py<3.2
  - zarr
  - dask
  - dask-cloudprovider
  - ujson
  - hvplot
  - kerchunk
  - pip:
    - s3fs
    - numcodecs
    - adlfs>=0.7.7
